version: "3.8"
services:

  mongodb:
    image: mongo:latest
    container_name: rag-mongo
    ports:
      - "27017:27017"

    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=moussa
    #   - MONGO_INITDB_ROOT_PASSWORD=moussa123
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
